version: '3.9'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true