# Dockerfile.dev
FROM node:20.11.1-alpine3.18

# Install dependencies for Playwright
RUN apk update && apk add --no-cache \
  git \
  bash \
  libc6-compat \
  chromium \
  nss \
  freetype \
  harfbuzz \
  ca-certificates \
  ttf-freefont \
  wget

# Install Playwright and its dependencies
RUN npm install -g playwright

WORKDIR /app
COPY package*.json ./
RUN npm install

# Install Playwright browsers
RUN npx playwright install --with-deps

COPY . .
EXPOSE 3000 3001 9229
CMD [ "npm", "run", "dev" ]
