# Dockerfile.dev
FROM mcr.microsoft.com/playwright:focal

# Install dependencies
RUN apt-get update && apt-get install -y git

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install node dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Expose the necessary ports
EXPOSE 3000 3001 9229

# Command to run your Next.js application
CMD ["npm", "run", "dev"]
