apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: next
        image: gcr.io/gvgamers/next:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
spec:
  selector:
    app: next
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
  type: ClusterIP

