apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  labels:
    app: next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
        - name: next
          image: gcr.io/gvgamers/next:latest
          env:
            - name: NODE_ENV
              value: production
            - name: AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: next-configmap
                  key: AUTH_URL
            - name: STORY_URL
              valueFrom:
                configMapKeyRef:
                  name: next-configmap
                  key: STORY_URL
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
spec:
  selector:
    app: next
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
