version: "3.9"
services:
  next:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"

  playwright:
    image: next-app-playwright
    build:
      context: ..
      dockerfile: Dockerfile.dev
    depends_on:
      - next
    environment:
      - CI=true
    volumes:
      - ../:/app:delegated
    working_dir: /app
    command: ["npx", "playwright", "test"]
