version: "3.9"
services:
  next:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/app:delegated
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
