version: "3.9"
services:
  next:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - URL
    volumes:
      - ../:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
