version: "3.9"
services:
  next:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ../:/app:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"
    environment:
      - NEXT_PUBLIC_AUTH_URL=${NEXT_PUBLIC_AUTH_URL}:4002
      - NEXT_PUBLIC_STORY_URL=${NEXT_PUBLIC_STORY_URL}:4000
    
  # playwright:
  #   image: next-app-playwright
  #   build:
  #     context: ..
  #     dockerfile: Dockerfile.dev
  #   depends_on:
  #     - next
  #   environment:
  #     - CI=true
  #   volumes:
  #     - ../:/app:delegated
  #   working_dir: /app
  #   command: ["npx", "playwright", "test"]
